<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AIPL2361LT06766" ignored="0" name="Go Rest Regression Test" tests="10" failures="3" timestamp="2020-06-04T12:19:30 IST" time="5.62" errors="0">
  <testcase name="createUserAPI" time="2.112" classname="com.qa.gorest.tests.CreateUserAPITest"/>
  <testcase name="createUserAPI" time="0.476" classname="com.qa.gorest.tests.CreateUserAPITest"/>
  <testcase name="getUserListAPITest" time="3.399" classname="com.qa.gorest.tests.GetUserAPITest"/>
  <testcase name="createUserAPI" time="0.482" classname="com.qa.gorest.tests.CreateUserAPITest"/>
  <testcase name="deleteUserTest" time="3.952" classname="com.qa.gorest.tests.DeleteUserAPITest"/>
  <testcase name="createUserAPI" time="0.43" classname="com.qa.gorest.tests.CreateUserAPITest"/>
  <testcase name="createUserAPI" time="0.511" classname="com.qa.gorest.tests.CreateUserAPITest"/>
  <testcase name="createUserAPI" time="1.212" classname="com.qa.gorest.tests.UpdateUserAPITest">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at com.qa.gorest.tests.UpdateUserAPITest.createUserAPI(UpdateUserAPITest.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken$0.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse$0.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 20 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- createUserAPI -->
  <testcase name="createUserHardCodedAPITest" time="0.491" classname="com.qa.gorest.tests.CreateUserAPITest">
    <failure type="java.lang.AssertionError" message="expected [Pratik1] but found [[null]]">
      <![CDATA[java.lang.AssertionError: expected [Pratik1] but found [[null]]
at com.qa.gorest.tests.CreateUserAPITest.createUserHardCodedAPITest(CreateUserAPITest.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- createUserHardCodedAPITest -->
  <testcase name="createUserAPIPUTTest_withSetter" time="0.973" classname="com.qa.gorest.tests.UpdateUserAPITest">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at com.qa.gorest.tests.UpdateUserAPITest.createUserAPIPUTTest_withSetter(UpdateUserAPITest.java:88)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken$0.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse$0.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 20 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- createUserAPIPUTTest_withSetter -->
</testsuite> <!-- Go Rest Regression Test -->
